### ISSUE TITLE
Footer - Redirección al home

### ISSUE THREAD

**Issue by castromaciel** [priscilabgmoya/proyecto-final-menu-frontEnd#51]
## Proceso

1. Ingresar a la página
2. Dar click en **inicio** en el footer

## Resultado esperado

Se espera redirigir al usuario a la página de inicio.

## Resultado actual

Si bien, la ruta cambia, no se muestran productos o información asociada.

## Captura

<img width="906" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/85483025-d0c6-4a50-a2ba-35880dd88bfd">

<img width="1013" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/c712bf3e-f64a-4727-83c6-56ed4e0ff505">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by priscilabgmoya** [comment]
buenas, ya lo modificamos!

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/5ec3ccd67d9dac9b97f6f86207894fa9413512bc

**Comment by castromaciel** [comment]
Se valida la solución.

<img width="1383" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/65246065-536b-40ee-a093-fc3482193b0f">

<img width="1438" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/a958649f-5b42-4d43-a090-f993136e26a4">
