### ISSUE TITLE
Registro de usuario

### ISSUE THREAD

**Issue by castromaciel** [priscilabgmoya/proyecto-final-menu-frontEnd#52]
## Proceso

1. Navegar hacia el registro
2. Diligenciar el formulario con campos validos

## Resultado esperado

Se espera registrar un usuario

## Resultado actual

Aún diligenciando los campos de manera exitosa, nos aarroja un error en el cual el mensaje no es claro para el usuario.

## Captura

<img width="1013" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/1b0137f9-1375-427b-bddf-8551a8181b35">

<img width="1015" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/e5edb8c7-5350-452c-a58a-0ed44f9a245d">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by priscilabgmoya** [comment]
resuelto

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/105519676/62156f31-0351-4c16-a8a4-f745e23908a9

**Comment by priscilabgmoya** [comment]
https://friky-sangucheria-v2.netlify.app/

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/b6f3b1ee32b53bfd1dc94e4cae5eb6e0858a3465

**Comment by castromaciel** [comment]
Se realizan pruebas en base a la corrección realizada: 

### Aparece el error

Request: 
```json
{
  "nombre": "Maciel",
  "email": "castromaciel@gmail.com",
  "contraseña": "prueba",
  "rol": "64cbba69610ffdd35dafa457",
  "estado": "64cd7db92a13bbf308f05c84"
}
```

Response:
```json
{
  "errors": [
    {
      "type": "field",
      "value": "prueba",
      "msg": "Contraseña es requerida",
      "path": "contraseña",
      "location": "body"
    }
  ]
}
```

<img width="1438" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/66160fb0-333a-4614-861a-d0a1bdd32626">

* **El mensaje no es diciente, se muestra un undefined**

### Se modifica la contraseña

<img width="1401" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/ddc9f0d8-5745-4d56-9885-a6f5988d217b">

**Comment by castromaciel** [comment]
Por favor, revisar el primer caso cuando la clave no cumple con los campos requeridos en el backend (o verificar la manera en la que se muestra el error)

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/2c1a32e4c1d3f8d37aace44eed2833eb78b1c22f

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/2c1a32e4c1d3f8d37aace44eed2833eb78b1c22f

**Comment by castromaciel** [comment]
Se realiza la validación:

<img width="1433" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/31d5e606-4af4-4d35-923a-a2ea11de27fe">

Si bien se muestra el mensaje desde el back, tener en cuenta lo siguiente:

* El usuario está digitando una contraseña, por lo que el mensaje es incorrecto.
* Se debería realiza una validación desde front informando qué campos no son validos y que reglas siguen los mismos (por ej: contraseña alfanumerica, o el campo nombre es solo alfabetico)
