### ISSUE TITLE
Administración - Filtro de busqueda

### ISSUE THREAD

**Issue by castromaciel** [priscilabgmoya/proyecto-final-menu-frontEnd#53]
## Proceso

1. Iniciar sesión con un usuario administrador
2. Realizar una busqueda

## Resultado esperado

Al realizar una busqueda, espero obtener la información filtrada.

## Resultado actual

Si bien, se realiza el filtro, no hay una especificación sobre que parametros se está realizando la busqueda. 
* Si la busqueda no especifica un parametro, debería poder realizarse una busqueda por todos los parametros en forma de texto.
* Si la busqueda especifica el parametro, ya se indica al usuario sobre que parametros se filtrará la información

### Busqueda por menú

Filtro por la categoría SANDWICH

<img width="1015" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/a1732e02-8ad9-441f-ae9c-a8b804314914">

No hay resultados

<img width="1018" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/f11d7b43-fa4a-4921-98ab-b518ee5d4d7c">

Cuando se busca por tabla, aparece

<img width="1011" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/ad09c3bb-bf01-4e09-98d4-1f43c70e2e9a">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by priscilabgmoya** [comment]
resuelto

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/9e15b4a82369cddbcfa6a66af69c9c550d1c4c3c

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/b6f3b1ee32b53bfd1dc94e4cae5eb6e0858a3465

**Comment by castromaciel** [comment]
Se realizan pruebas,

Iniciamos sesión con un usuario admin, y se visualizan los placeholders en los inputs:

Pedidos:
<img width="1022" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/92c34ccb-586e-409a-875b-a9c52e4d8abc">

Menu:
<img width="1018" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/f5ff3ffc-e489-4d0b-9d52-e512c70baf58">

Usuarios: 
<img width="1010" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/dad34c32-2630-4955-84cc-7c2dc48d15a4">
