### ISSUE TITLE
Home - Agregar productos al carrito

### ISSUE THREAD

**Issue by castromaciel** [priscilabgmoya/proyecto-final-menu-frontEnd#54]
## Proceso

La descripción del proceso se encuentra con las capturas.

## Resultado esperado

Poder ir agregando progresivamente los productos al carrito. Y que estos productos sean independientes (No dependan de la posicion en la que se encuentran)

## Resultado actual

Si voy cambiando entre paginas, permanece un producto que no corresponde al agregado inicialmente.

### Agregamos un producto

<img width="1063" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/45214d28-0ce7-464c-a2d2-b72dacc1c6d7">

### Cambiamos a la pantalla 2, aparece un menu cargado.

<img width="1060" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/9523ca51-e545-41ac-83ac-0b3bcaa35bf5">

### Se agrega uno adicional y nos dirigmos a la pantalla 3

<img width="1061" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/eb03119f-a03a-4372-b129-e40d88cb8e1a">

### Aparecen 2 menúes cargados

<img width="1060" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/9f24bf8c-22b8-4acf-8ea1-13585753d1ff">

### Eliminamos los dos y nos dirigamos a la pantalla 1

<img width="1054" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/2bb3349f-80e9-4037-a320-265c34b0645b">

### Se eliminan todos los elementos de la primer columna

<img width="1054" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/00719622-cc3d-4441-8d32-d0114b040201">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by priscilabgmoya** [comment]
resuelto

**Comment by priscilabgmoya** [comment]
https://friky-sangucheria-v2.netlify.app/

**Comment by castromaciel** [comment]
El defecto todavía persiste: 

**Evidencia:** 

https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/6a41d7a3-3259-4998-8f67-cc33a057660a

**Comment by priscilabgmoya** [comment]
profe disculpe pero no funciona así como lo hace usted, nosotros lo pensamos de otra manera, para agregar otro producto, tiene que agregarlo primero al carrito y después seguir agregando...

**Comment by castromaciel** [comment]
En todo caso, una de las posibles soluciones puede ser:  

* Deshabilitar el botón de siguiente si es que se aumento la cantidad pero no se han agregado productos al carrito
* Antes de continuar informar al usuario que se va a cambiar a otra pestaña
* Eliminar la cantidad de productos antes de continuar a la siguiente pestaña

Por como podemos ver en la evidencia

> El defecto todavía persiste:
> 
> **Evidencia:**
> 
>  Screen.Recording.2023-09-27.at.18.21.05.mov

Se estan pisando los productos ya sea con cantidades que no eligió un usuario, o eliminando cantidades que ya habia seleccionado pero no agregó al carrito

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/560b789662b0cc7f9081f02e5858287f97670c34

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/d143f3caa2ab3012bb91755755c693958ddc8634

se actualiza notificación de producto agregado.

**Comment by castromaciel** [comment]
Buenos días, se revisa el inconveniente y se encuentra solucionado:

<img width="1006" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/a99c8dd6-c3aa-4722-adaf-49e13a1380c8">

<img width="1000" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/8d250007-f7fb-4b07-a8a8-d7c34d21b579">


**Como recomendación:** 
* Evitar el uso de las alertas nativas del objeto `window`.


<img width="755" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/0b60dc82-4de4-49ae-a644-f3a494a02a22">
