### ISSUE TITLE
Modal - Carrito

### ISSUE THREAD

**Issue by castromaciel** [priscilabgmoya/proyecto-final-menu-frontEnd#55]
## Proceso

1. Agregar productos al carrito
2. Abrir el carrito

## Resultado esperado

Al agregar los productos al carrito, se espera ver un resumen (Total) de lo que se va a gastar.  Este total tiene que ser acorde a los productos agregados.

## Resultado actual

La suma de los productos no coincide con el total mostrado.

## Captura

<img width="308" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/be8b5aa0-3009-4665-8ac5-74f58d2a1a97">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by priscilabgmoya** [comment]
resuelto

**Comment by priscilabgmoya** [comment]
![image](https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/105519676/63ce78ad-110c-491c-a20d-d319e1c76c97)

**Comment by priscilabgmoya** [comment]
https://friky-sangucheria-v2.netlify.app/

**Comment by castromaciel** [comment]
Se valida la solución 

<img width="423" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/37f5838e-f4ae-4633-a9f3-8cf9e359d108">
