### ISSUE TITLE
Error al realizar una compra

### ISSUE THREAD

**Issue by castromaciel** [priscilabgmoya/proyecto-final-menu-frontEnd#56]
## Proceso

1. Iniciar sesión
2. Agregar productos al carrito
3. Realizar una compra

## Resultado esperado

Se espera que al cargar los pedidos y dar click en el boton "ir a pagar", se visualicen los medios de pagos (o en su defecto, realizar una compra)

## Resultado actual

El botón no realiza ninguna acción para el usuario. 

Para el desarrollador, se visualiza un fallo en el endpoint `api/V1/create_preference`. (Están apuntando a localhost)

## Captura

<img width="1128" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/d3bb6853-89d7-49be-a14c-71021958a80e">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by priscilabgmoya** [comment]
resuelto

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/b6f3b1ee32b53bfd1dc94e4cae5eb6e0858a3465

**Comment by castromaciel** [comment]
Se valida la solución 

<img width="1370" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/175a9c55-4c1c-4ee8-bdd4-3dc39c72f825">
