### ISSUE TITLE
Cambio de clave

### ISSUE THREAD

**Issue by castromaciel** [priscilabgmoya/proyecto-final-menu-frontEnd#57]
## Proceso

1. Iniciar sesión
2. Dirigirse a cuenta
3. Realizar un cambio de clave

## Resultado esperado

Realizar un cambio de clave exitoso.

## Resultado actual

Al cambiar la clave, no se debería retornar información importante del usuario (contraseñas), mucho menos por consola. 

## Captura

<img width="1323" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/aba3cb68-5959-4c00-9a5d-65d88fb68c9e">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by priscilabgmoya** [comment]
resulto

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/b6f3b1ee32b53bfd1dc94e4cae5eb6e0858a3465

**Comment by castromaciel** [comment]
Se valida la solución

<img width="1312" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/e8ce52dd-c145-4882-8351-a6efddb5c11a">
