### ISSUE TITLE
Perfil Usuario

### ISSUE THREAD

**Issue by castromaciel** [priscilabgmoya/proyecto-final-menu-frontEnd#58]
## Proceso

1. Iniciar sesión
2. Dirigirse a cuenta

## Resultado esperado

Ver la información del usuario loggeado

## Resultado actual

Se muestra un mensaje de error la primera vez al intentar visualizar la información

## Captura

<img width="323" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/c0f7c9d7-6085-4d50-8c48-8ed9eb894684">

<img width="1336" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/cf016490-3513-463b-9fad-abe50c305f82">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by priscilabgmoya** [comment]
resulto

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/b6f3b1ee32b53bfd1dc94e4cae5eb6e0858a3465

**Comment by castromaciel** [comment]
Se valida la solución

<img width="325" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/02ec1e5e-db6c-4cbd-8922-4bfae94e76bd">
