### ISSUE TITLE
Admin - Nuevo menu

### ISSUE THREAD

**Issue by castromaciel** [priscilabgmoya/proyecto-final-menu-frontEnd#59]
## Proceso

1. Iniciar sesión con un usuario administrador
2. Dar click en nuevo menu
3. Diligenciar el formulario y crear menu

## Resultado esperado

Se espera ver en la lista de menús el creado en el formulario

## Resultado actual

No se crea un menú, no se informa el error al usuario.

Para el desarrollador: Hay un error en consola de una funcion o metodo no definido. Adicional, no sale ninguna petición al backend.

## Captura

<img width="1436" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/541d04ad-deec-45fd-9723-d350a025d8d6">

<img width="1440" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/0640c516-36c9-41c2-ab56-38cb310cc14d">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by priscilabgmoya** [comment]
resuelto

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/b6f3b1ee32b53bfd1dc94e4cae5eb6e0858a3465

**Comment by castromaciel** [comment]
Se realizan las prubas,

iniciamos sesión con usuario administrador: 

<img width="1439" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/3c2781ee-8cff-4bd6-a010-7ee7374ed6d4">

<img width="1439" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/10742b64-75e6-4530-a774-3a8d934b61c6">

<img width="1440" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/dae584a0-3c41-4d51-bf04-424199eb45e3">

Persiste el error con un Mensaje "Token no valido", verificar el manejo de roles del lado del backend.

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/87ca81c61523e06fa1f13fd761ef7ea4d5d02603

**Comment by castromaciel** [comment]
Solucionado:

<img width="1440" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/c09312e3-cd01-4c45-8afc-abe06006a041">

Recomendación:

Buscar acerca de como mostrar un panel o un aviso al usuario final para que permita o deniegue el uso de las mismas.
Eliminar los debuggers
