### ISSUE TITLE
Admin - Modificar usuario

### ISSUE THREAD

**Issue by castromaciel** [priscilabgmoya/proyecto-final-menu-frontEnd#60]
## Proceso

Se encuentra descrito en las capturas.

## Resultado esperado

Realizar la edicion de un usuario

## Resultado actual

No se permite la edición en distintos puntos

## Captura

Iniciar sesión como admin

<img width="846" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/6490ac61-edf9-431f-8d6d-c6c8bb9b27aa">

<img width="848" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/09447f49-4c27-4871-b73a-a0c4a32feb38">

Editamos un usuario

<img width="844" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/58abb048-3256-4bdd-8e27-93f9ee81f035">

<img width="852" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/3327f74f-bf2b-4f1e-8ad8-2122b81e887f">

Da un error con un nombre de usuario diferente

<img width="1440" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/352ca82c-3b9e-475c-8d7d-ccfbb1eed4c9">

## Adicional: 

* Los campos nombre y correos no se pueden editar. Si esto es alguna implementación del equipo, lo recomendable sería presentarlos con la información pero con la propiedad `disabled`
* No permite la eliminación de los usuarios 
<img width="1439" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/b00e4691-1572-4a78-a258-c10b174f2e1f">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by priscilabgmoya** [comment]
resuelto

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/b6f3b1ee32b53bfd1dc94e4cae5eb6e0858a3465

**Comment by castromaciel** [comment]
se realizan pruebas:

<img width="1017" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/5bda4337-cfd5-4819-ad51-19b891667773">

Damos click en guardar cambios:

<img width="1436" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/ff280cb7-deca-41de-8e73-8dde091faa10">

Da un error en consola

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/87ca81c61523e06fa1f13fd761ef7ea4d5d02603

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/3984131c1d0d7778995ea91704e681418c8cafc5

**Comment by castromaciel** [comment]
Solucionado permitiendo las cookies desde el browser

<img width="1434" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/384569cb-c646-4298-951c-78a88dd4273c">

<img width="1435" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/a0c5fc11-b484-4767-8310-c1cb5a79c5ab">


**Recomendación**: 
* Buscar acerca de como mostrar un panel o un aviso al usuario final para que **permita** o **deniegue** el uso de las mismas.
* Eliminar los debuggers
