### ISSUE TITLE
Admin - Pedidos

### ISSUE THREAD

**Issue by castromaciel** [priscilabgmoya/proyecto-final-menu-frontEnd#61]
## Proceso

1. Iniciar sesión como admin
2. Ir a pedidos
3. Completar un pedido
4. Da un error en el token

## Resultado esperado

Se espera que el usuario admin, pueda finalizar los pedidos pendientes

## Resultado actual

Actualmente, no permite la edición de un pedido en curso

## Captura

<img width="989" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/3db1675b-b124-4292-b073-41cce86d0b01">

<img width="739" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/6af24a7e-829f-406e-8008-09f08ac98f4c">

<img width="1436" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/269dc7c3-6441-44ab-863d-4d67d80daee2">

## Notas

Cualquier duda/consulta pueden contactarme vía mail, o por canal de slack de la comunidad de Rolling.

**Comment by priscilabgmoya** [comment]
resuelto

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/b6f3b1ee32b53bfd1dc94e4cae5eb6e0858a3465

**Comment by castromaciel** [comment]
Se realizan pruebas:

<img width="1015" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/220a88dd-b5ed-4615-900c-9fd66450496d">


El error persiste:

<img width="1435" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/39514b06-43c5-4da1-a4fd-8a3cc1684ce1">

**Comment by priscilabgmoya** [comment]
https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/commit/3984131c1d0d7778995ea91704e681418c8cafc5

**Comment by castromaciel** [comment]
Se puede editar el pedido:

<img width="1437" alt="image" src="https://github.com/priscilabgmoya/proyecto-final-menu-frontEnd/assets/83432755/d06a52f5-f4af-4033-ace5-24363e17d9c8">

Recomendación:

Buscar acerca de como mostrar un panel o un aviso al usuario final para que permita o deniegue el uso de las mismas.
Eliminar los debuggers
